### ISSUE TITLE
Remove javascript example from README

### ISSUE THREAD

**Issue by fpgirard** [dgreif/ring-client-example#3]
The example.js has been removed but the reference to it in the README.md remains:

_**JavaScript Example

The JavaScript example can be found in the [example.js](https://github.com/dgreif/ring-client-example/blob/main/example.js) file. Once you have followed the Authentication steps, you can run this example by running npm run js-example**_

I'd recommend removing it for clarity.

**Comment by dgreif** [comment]
Thanks for the heads up! I removed the JS example a while ago because it was too easy for it to get out of date, but I forgot to update the readme 😄
