### ISSUE TITLE
Example finds location and reports cameras correctly then blocks

### ISSUE THREAD

**Issue by fpgirard** [dgreif/ring-client-example#4]
Hi Dusty - my apologies for being a complete n00b on typescript but I'm following your instructions very carefully on this example and can properly authenticate to my ring system in my location.   The script properly connects and refreshes my token but fails to subscribe or get the camera devices.  It simply stalls upon reporting the location (see below).

Any insight you might suggest on tools that I can use to debug this would be great appreciated.  While I'm a decent c++ and python coder, npm and typescript are completely foreign to me.

p

```
pascal@frenzy:~/src/ring/ring-client-example$ npm run ts-example

> ring-client-example@1.0.0 ts-example
> tsc && node lib/example.js

Found 1 location(s) with 2 camera(s).
Refresh Token GzSt1llg2CVePa4GFYixrAoQmV11N4xTbqvrrt7VWl0zN-nj_loG7Yaxh26Kj5esikW_JPb58Z0n9FXPMOcp8blsX6-dAjyrjKCIDB-GN4lPNFbQ4BGRGetw-RrI2E76sv32JQbjTwTsB4D2ivtuwNS2Da2sKU6LQ
**** Connected to location Bethesda - 67bf6ba3-d805-442e-a1f8-784194878b50
```

**Comment by dgreif** [comment]
The last line printed should be `Listening for motion and doorbell presses on your cameras.`, at which point it will only log additional information when there is a doorbell press or motion.

If you are not seeing that line, then it's possible you have a Ring Alarm or Ring Lighting Bridge which is registered to your account, but not currently online.

**Comment by fpgirard** [comment]
Or in my case, no Ring Alarm or Ring Lightning Bridge - just a doorbell and a security light with camera....   I overlooked the fact that I needed a Ring Alarm base station.  Thanks for pointing that out!  Have a great weekend Dusty.
